name: Publish Workflow

on:
  release:
    types: [published]

jobs:
  entire_workflow:
    name: Release Process
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm ci

    - name: Run build
      run: npm run build

    - name: Release
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Action"
    - name: Initialise the NPM config
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: NPM Release
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: npm run release
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
